import axios from 'axios';
import { loadConfig, saveConfig } from '../config/configManager.js';

const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';

/**
 * Get OpenRouter API key from config
 * @returns {Promise<string|null>} API key or null
 */
export async function getOpenRouterKey() {
  try {
    const cfg = await loadConfig();
    return cfg.openRouterKey || null;
  } catch (err) {
    return null;
  }
}

/**
 * Generate a solution for a GitHub issue using OpenRouter
 * @param {string} issueTitle - Issue title
 * @param {string} issueBody - Issue description/body
 * @param {string} repo - Repository name (for context)
 * @param {string} language - Programming language (optional)
 * @returns {Promise<string>} AI-generated solution
 */
export async function generateIssueSolution(issueTitle, issueBody, repo, language = 'JavaScript') {
  const apiKey = await getOpenRouterKey();
  
  if (!apiKey) {
    throw new Error('OpenRouter API key not configured. Run: contriflow config --set-ai-key <your-key>');
  }

  const prompt = buildSolutionPrompt(issueTitle, issueBody, repo, language);

  try {
    const response = await axios.post(
      OPENROUTER_API_URL,
      {
        model: 'openrouter/auto',
        messages: [
          {
            role: 'user',
            content: prompt
          }
        ],
        temperature: 0.7,
        max_tokens: 2000
      },
      {
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'HTTP-Referer': 'https://github.com/contriflow/contriflow-cli',
          'X-Title': 'ContriFlow CLI'
        }
      }
    );

    if (response.data && response.data.choices && response.data.choices.length > 0) {
      return response.data.choices[0].message.content;
    }
    throw new Error('Invalid response from OpenRouter API');
  } catch (err) {
    if (err.response && err.response.status === 401) {
      throw new Error('Invalid OpenRouter API key. Check your configuration.');
    }
    throw new Error(`AI API Error: ${err.message}`);
  }
}

/**
 * Build a prompt for issue solving
 * @param {string} title - Issue title
 * @param {string} body - Issue body
 * @param {string} repo - Repository name
 * @param {string} language - Programming language
 * @returns {string} Formatted prompt
 */
function buildSolutionPrompt(title, body, repo, language) {
  return `You are an expert software developer helping to solve GitHub issues.

Repository: ${repo}
Issue Title: ${title}
Programming Language: ${language}

Issue Description:
${body}

Please provide:
1. A brief analysis of the issue
2. Proposed solution(s)
3. Code example/patch if applicable

Format your response with clear sections. If code is provided, wrap it in markdown code blocks with the language specified (${language}).`;
}

/**
 * Generate a code patch from AI solution
 * @param {string} solution - AI-generated solution
 * @param {string} filename - File to patch
 * @returns {string} Formatted patch content
 */
export function formatAsPatch(solution, filename) {
  const timestamp = new Date().toISOString();
  const header = `--- a/${filename}
+++ b/${filename}
@@ Patch Generated by ContriFlow AI Solver @@
Generated: ${timestamp}

ANALYSIS AND PROPOSED SOLUTION:
${solution}

Note: This is an AI-generated suggestion. Please review and modify as needed before applying.`;

  return header;
}

/**
 * Extract code blocks from AI response
 * @param {string} response - AI response text
 * @returns {Array<string>} Array of code blocks
 */
export function extractCodeBlocks(response) {
  const codeBlockRegex = /```(?:\w+)?\n([\s\S]*?)```/g;
  const blocks = [];
  let match;

  while ((match = codeBlockRegex.exec(response)) !== null) {
    blocks.push(match[1]);
  }

  return blocks;
}

/**
 * Store API key in config
 * @param {string} apiKey - OpenRouter API key
 * @throws {Error} If config save fails
 */
export async function setOpenRouterKey(apiKey) {
  try {
    const cfg = await loadConfig();
    cfg.openRouterKey = apiKey;
    await saveConfig(cfg);
  } catch (err) {
    throw new Error(`Failed to save API key: ${err.message}`);
  }
}
